/**
 * English
 *
 * LCD Menu Messages
 * Please note these are limited to 17 characters!
 *
 */
#ifndef LANGUAGE_EN_H
#define LANGUAGE_EN_H

#define MSG_AXIS "Axis"
#define MSG_WIZARD "Wizard"
#define MSG_EXIT "Exit"
#define MSG_BED_LEVEL "Bed Level"
#define MSG_CLEAN_NOZZLE "Cleaning"
#define MSG_CHANGE_FILAMENT "NewFilament"
#define MSG_HEAT "Preheat"
		//#define MSG_COOL "Cooldown"
#define MSG_HOME "HomeAll"
#define MSG_DISABLE "Disable"
#define MSG_ENABLE "Enable"
#define MSG_CONTINUE "Continue"
#define MSG_RESTART "Restart"
#define MSG_TOGGLE "Toggle"
#define MSG_DIAL "Dial"
        
#define MSG_DIAL_SENSITIVITY_1 "Toggle the dial"
#define MSG_DIAL_SENSITIVITY_2 "sensitivity between"
#define MSG_DIAL_SENSITIVITY_3 "high or low."

#define MSG_WIZARD1_1 "Bed Level Wizard 1/6"
#define MSG_WIZARD1_2 "Ensure the print"
#define MSG_WIZARD1_3 "surface is clipped"
#define MSG_WIZARD1_4 "on and the nozzle"
#define MSG_WIZARD1_5 "is free of debris"
#define MSG_WIZARD1_6 "before continuing."
		
#define MSG_WIZARD2_1 "Bed Level Wizard 2/6"
#define MSG_WIZARD2_2 "Please Wait..."
#define MSG_WIZARD2_3 "Heating..."

		
#define MSG_WIZARD3_1 "Bed Level Wizard 3/6"
#define MSG_WIZARD3_2 "Turn the thumb screw"
#define MSG_WIZARD3_3 "below the nozzle"
#define MSG_WIZARD3_4 "until there is a"
#define MSG_WIZARD3_5 "hairline gap between"
#define MSG_WIZARD3_6 "the nozzle and bed."
				
#define MSG_WIZARD4_1 "Bed Level Wizard 4/6"
		
#define MSG_WIZARD5_1 "Bed Level Wizard 5/6"
		
#define MSG_WIZARD6_1 "Bed Level Wizard 6/6"
#define MSG_WIZARD6_2 "Your bed should now"
#define MSG_WIZARD6_3 "be leveled! Press"
#define MSG_WIZARD6_4 "restart if you"
#define MSG_WIZARD6_5 "would like to"
#define MSG_WIZARD6_6 "try again."
		
#define MSG_CLEAN_WIZARD1_1 "Change Filament 1/4"
#define MSG_CLEAN_WIZARD1_2 "Use this wizard to"
#define MSG_CLEAN_WIZARD1_3 "change the filamant"
#define MSG_CLEAN_WIZARD1_4 "inside your machine."
#define MSG_CLEAN_WIZARD1_5 "Press continue when"
#define MSG_CLEAN_WIZARD1_6 "ready."
		
#define MSG_CLEAN_WIZARD2_1 "Change Filament 2/4"
#define MSG_CLEAN_WIZARD2_2 "Please wait..."
#define MSG_CLEAN_WIZARD2_3 "Heating up..."

#define MSG_CLEAN_WIZARD3_1 "Change Filament 3/4"
#define MSG_CLEAN_WIZARD3_2 "Pull the filament out"
#define MSG_CLEAN_WIZARD3_3 "(if any). Insert new"
#define MSG_CLEAN_WIZARD3_4 "filament and push"
#define MSG_CLEAN_WIZARD3_5 "down until new color"
#define MSG_CLEAN_WIZARD3_6 "comes out of hotend."
		
#define MSG_CLEAN_WIZARD4_1 "Change Filament 4/4"
#define MSG_CLEAN_WIZARD4_2 "You're done! Trim the"
#define MSG_CLEAN_WIZARD4_3 "tip of the filament"
#define MSG_CLEAN_WIZARD4_4 "of the previous spool"
#define MSG_CLEAN_WIZARD4_5 "and store it away in"
#define MSG_CLEAN_WIZARD4_6 "a cool dry place."
		
#define MSG_CLEAN_WIZARD5_1 "Cleaning Wizard 5/7"
#define MSG_CLEAN_WIZARD5_2 "Pull out filament,"
#define MSG_CLEAN_WIZARD5_3 "cut off the tip and"
#define MSG_CLEAN_WIZARD5_4 "reinsert filament."
		
#define MSG_CLEAN_WIZARD6_1 "Cleaning Wizard 6/7"
#define MSG_CLEAN_WIZARD7_1 "Cleaning Wizard 7/7"
        
#define MSG_EXTRUDE1_1 "Extrude Test 1/3"
#define MSG_EXTRUDE1_2 "This will heat up"
#define MSG_EXTRUDE1_3 "then extrude 10mm"
#define MSG_EXTRUDE1_4 "of filament"
        
        
#define MSG_EXTRUDE2_1 "Extrude Test 2/3"
#define MSG_EXTRUDE2_2 "Please wait..."
#define MSG_EXTRUDE2_3 "Heating up..."
        
#define MSG_EXTRUDE3_1 "Extrude Test 3/3"
#define MSG_EXTRUDE3_2 "10mm extruded."
#define MSG_EXTRUDE3_3 "Press restart to"
#define MSG_EXTRUDE3_4 "extrude again."

#define WELCOME_MSG                         MACHINE_NAME " ready."
#define MSG_SD_INSERTED                     "Card inserted"
#define MSG_SD_REMOVED                      "Card removed"
#define MSG_MAIN                            "Main"
#define MSG_AUTOSTART                       "Autostart"
#define MSG_DISABLE_STEPPERS                "Disable steppers"
#define MSG_AUTO_HOME                       "Auto home"
#define MSG_SET_HOME_OFFSETS                "Set home offsets"
#define MSG_SET_ORIGIN                      "Set origin"
#define MSG_PREHEAT_PLA                     "Preheat PLA"
#define MSG_PREHEAT_PLA0                    "Preheat PLA 1"
#define MSG_PREHEAT_PLA1                    "Preheat PLA 2"
#define MSG_PREHEAT_PLA2                    "Preheat PLA 3"
#define MSG_PREHEAT_PLA012                  "Preheat PLA All"
#define MSG_PREHEAT_PLA_BEDONLY             "Preheat PLA Bed"
#define MSG_PREHEAT_PLA_SETTINGS            "Preheat PLA conf"
#define MSG_PREHEAT_ABS                     "Preheat ABS"
#define MSG_PREHEAT_ABS0                    "Preheat ABS 1"
#define MSG_PREHEAT_ABS1                    "Preheat ABS 2"
#define MSG_PREHEAT_ABS2                    "Preheat ABS 3"
#define MSG_PREHEAT_ABS012                  "Preheat ABS All"
#define MSG_PREHEAT_ABS_BEDONLY             "Preheat ABS Bed"
#define MSG_PREHEAT_ABS_SETTINGS            "Preheat ABS conf"
#define MSG_COOLDOWN                        "Cooldown"
#define MSG_SWITCH_PS_ON                    "Switch power on"
#define MSG_SWITCH_PS_OFF                   "Switch power off"
#define MSG_EXTRUDE                         "Extrude"
#define MSG_RETRACT                         "Retract"
#define MSG_MOVE_AXIS                       "Move axis"
#define MSG_MOVE_X                          "Move X"
#define MSG_MOVE_Y                          "Move Y"
#define MSG_MOVE_Z                          "Move Z"
#define MSG_MOVE_E                          "Extruder"
#define MSG_MOVE_E1                         "Extruder2"
#define MSG_MOVE_E2                         "Extruder3"
#define MSG_MOVE_01MM                       "Move 0.1mm"
#define MSG_MOVE_1MM                        "Move 1mm"
#define MSG_MOVE_10MM                       "Move 10mm"
#define MSG_SPEED                           "Speed"
#define MSG_NOZZLE                          "Nozzle"
#define MSG_NOZZLE1                         "Nozzle2"
#define MSG_NOZZLE2                         "Nozzle3"
#define MSG_BED                             "Bed"
#define MSG_FAN_SPEED                       "Fan speed"
#define MSG_FLOW                            "Flow"
#define MSG_FLOW0                           "Flow 0"
#define MSG_FLOW1                           "Flow 1"
#define MSG_FLOW2                           "Flow 2"
#define MSG_CONTROL                         "Control"
#define MSG_MIN                             " \002 Min"
#define MSG_MAX                             " \002 Max"
#define MSG_FACTOR                          " \002 Fact"
#define MSG_AUTOTEMP                        "Autotemp"
#define MSG_ON                              "On "
#define MSG_OFF                             "Off"
#define MSG_PID_P                           "PID-P"
#define MSG_PID_I                           "PID-I"
#define MSG_PID_D                           "PID-D"
#define MSG_PID_C                           "PID-C"
#define MSG_ACC                             "Accel"
#define MSG_VXY_JERK                        "Vxy-jerk"
#define MSG_VZ_JERK                         "Vz-jerk"
#define MSG_VE_JERK                         "Ve-jerk"
#define MSG_VMAX                            "Vmax "
#define MSG_X                               "x"
#define MSG_Y                               "y"
#define MSG_Z                               "z"
#define MSG_E                               "e"
#define MSG_VMIN                            "Vmin"
#define MSG_VTRAV_MIN                       "VTrav min"
#define MSG_AMAX                            "Amax "
#define MSG_A_RETRACT                       "A-retract"
#define MSG_XSTEPS                          "Xsteps/mm"
#define MSG_YSTEPS                          "Ysteps/mm"
#define MSG_ZSTEPS                          "Zsteps/mm"
#define MSG_ESTEPS                          "Esteps/mm"
#define MSG_TEMPERATURE                     "Temperature"
#define MSG_MOTION                          "Motion"
#define MSG_VOLUMETRIC                      "Filament"
#define MSG_VOLUMETRIC_ENABLED		        "E in mm3"
#define MSG_FILAMENT_SIZE_EXTRUDER_0        "Fil. Dia. 1"
#define MSG_FILAMENT_SIZE_EXTRUDER_1        "Fil. Dia. 2"
#define MSG_FILAMENT_SIZE_EXTRUDER_2        "Fil. Dia. 3"
#define MSG_CONTRAST                        "LCD contrast"
#define MSG_STORE_EPROM                     "Store memory"
#define MSG_LOAD_EPROM                      "Load memory"
#define MSG_RESTORE_FAILSAFE                "Restore failsafe"
#define MSG_REFRESH                         "Refresh"
#define MSG_WATCH                           "Info screen"
#define MSG_PREPARE                         "Prepare"
#define MSG_TUNE                            "Tune"
#define MSG_PAUSE_PRINT                     "Pause print"
#define MSG_RESUME_PRINT                    "Resume print"
#define MSG_STOP_PRINT                      "Stop print"
#define MSG_CARD_MENU                       "Print from SD"
#define MSG_NO_CARD                         "No SD card"
#define MSG_DWELL                           "Sleep..."
#define MSG_USERWAIT                        "Wait for user..."
#define MSG_RESUMING                        "Resuming print"
#define MSG_PRINT_ABORTED                   "Print aborted"
#define MSG_NO_MOVE                         "No move."
#define MSG_KILLED                          "KILLED. "
#define MSG_STOPPED                         "STOPPED. "
#define MSG_CONTROL_RETRACT                 "Retract mm"
#define MSG_CONTROL_RETRACT_SWAP            "Swap Re.mm"
#define MSG_CONTROL_RETRACTF                "Retract  V"
#define MSG_CONTROL_RETRACT_ZLIFT           "Hop mm"
#define MSG_CONTROL_RETRACT_RECOVER         "UnRet +mm"
#define MSG_CONTROL_RETRACT_RECOVER_SWAP    "S UnRet+mm"
#define MSG_CONTROL_RETRACT_RECOVERF        "UnRet  V"
#define MSG_AUTORETRACT                     "AutoRetr."
#define MSG_FILAMENTCHANGE                  "Change filament"
#define MSG_INIT_SDCARD                     "Init. SD card"
#define MSG_CNG_SDCARD                      "Change SD card"
#define MSG_ZPROBE_OUT                      "Z probe out. bed"
#define MSG_POSITION_UNKNOWN                "Home X/Y before Z"
#define MSG_ZPROBE_ZOFFSET                  "Z Offset"
#define MSG_BABYSTEP_X                      "Babystep X"
#define MSG_BABYSTEP_Y                      "Babystep Y"
#define MSG_BABYSTEP_Z                      "Babystep Z"
#define MSG_ENDSTOP_ABORT                   "Endstop abort"

#define MSG_RECTRACT                        "Rectract"

#ifdef DELTA_CALIBRATION_MENU
    #define MSG_DELTA_CALIBRATE             "Delta Calibration"
    #define MSG_DELTA_CALIBRATE_X           "Calibrate X"
    #define MSG_DELTA_CALIBRATE_Y           "Calibrate Y"
    #define MSG_DELTA_CALIBRATE_Z           "Calibrate Z"
    #define MSG_DELTA_CALIBRATE_CENTER      "Calibrate Center"
#endif // DELTA_CALIBRATION_MENU

#endif // LANGUAGE_EN_H
